spring:
  application:
    name: MyHappyPlant

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://techlabz.us.to:3306/MyHappyPlants?serverTimezone=Europe/Stockholm&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false