// Dummy user plant objects based on EditUserPlantRequest/CreateUserPlantRequest DTO
export const dummyUserPlants = [
  {
    id: 1,
    nickname: "Sunny",
    lastWatered: "2026-02-24",
    waterFrequency: 7,
    trefleId: 123456,
    commonName: "Fern",
    scientificName: "Pteridophyta",
    familyCommonName: "Polypodiopsida",
    image: "/assets/plant1.png",
  },
  {
    id: 2,
    nickname: "Fernie",
    lastWatered: "2026-02-20",
    waterFrequency: 5,
    trefleId: 654321,
    commonName: "Cactus",
    scientificName: "Cactaceae",
    familyCommonName: "Opuntioideae",
    image: "/assets/plant2.png",
  },
  {
    id: 3,
    nickname: "Cactus Jack",
    lastWatered: "2026-02-12",
    waterFrequency: 14,
    trefleId: 789012,
    commonName: "Swiss Cheese Plant",
    scientificName: "Monstera deliciosa",
    familyCommonName: "Araceae",
    image: "/assets/plant3.png",
  },
  {
    id: 4,
    nickname: "Aloe",
    lastWatered: "2026-02-03",
    waterFrequency: 10,
    trefleId: 111111,
    commonName: "Aloe Vera",
    scientificName: "Aloe barbadensis",
    familyCommonName: "Asphodelaceae",
    image: "/assets/plant4.png",
  },
  {
    id: 5,
    nickname: "Fikus",
    lastWatered: "2026-02-07",
    waterFrequency: 6,
    trefleId: 222222,
    commonName: "Fig Tree",
    scientificName: "Ficus carica",
    familyCommonName: "Moraceae",
    image: "/assets/plant5.png",
  },
  {
    id: 6,
    nickname: "Bonsai",
    lastWatered: "2026-02-02",
    waterFrequency: 4,
    trefleId: 333333,
    commonName: "Bonsai",
    scientificName: "Juniperus",
    familyCommonName: "Cupressaceae",
    image: "/assets/plant6.png",
  },
  {
    id: 7,
    nickname: "Palma",
    lastWatered: "2026-02-08",
    waterFrequency: 8,
    trefleId: 444444,
    commonName: "Palm",
    scientificName: "Arecaceae",
    familyCommonName: "Coryphoideae",
    image: "/assets/plant7.png",
  },
  {
    id: 8,
    nickname: "Ros",
    lastWatered: "2026-02-06",
    waterFrequency: 3,
    trefleId: 555555,
    commonName: "Rose",
    scientificName: "Rosa",
    familyCommonName: "Rosaceae",
    image: "/assets/plant8.png",
  },
  {
    id: 9,
    nickname: "Tulpan",
    lastWatered: "2026-02-04",
    waterFrequency: 2,
    trefleId: 666666,
    commonName: "Tulip",
    scientificName: "Tulipa",
    familyCommonName: "Liliaceae",
    image: "/assets/plant9.png",
  },
  {
    id: 10,
    nickname: "Lavendel",
    lastWatered: "2026-02-09",
    waterFrequency: 9,
    trefleId: 777777,
    commonName: "Lavender",
    scientificName: "Lavandula",
    familyCommonName: "Lamiaceae",
    image: "/assets/plant10.png",
  },
  {
    id: 11,
    nickname: "Bambu",
    lastWatered: "2026-02-11",
    waterFrequency: 12,
    trefleId: 888888,
    commonName: "Bamboo",
    scientificName: "Bambusoideae",
    familyCommonName: "Poaceae",
    image: "/assets/plant11.png",
  },
  {
    id: 12,
    nickname: "Krysantemum",
    lastWatered: "2026-02-12",
    waterFrequency: 5,
    trefleId: 999999,
    commonName: "Chrysanthemum",
    scientificName: "Chrysanthemum",
    familyCommonName: "Asteraceae",
    image: "/assets/plant12.png",
  },
  {
    id: 13,
    nickname: "Orkidé",
    lastWatered: "2026-02-13",
    waterFrequency: 7,
    trefleId: 101010,
    commonName: "Orchid",
    scientificName: "Orchidaceae",
    familyCommonName: "Epidendroideae",
    image: "/assets/plant13.png",
  },
  {
    id: 14,
    nickname: "Viol",
    lastWatered: "2026-02-14",
    waterFrequency: 3,
    trefleId: 121212,
    commonName: "Violet",
    scientificName: "Viola",
    familyCommonName: "Violaceae",
    image: "/assets/plant14.png",
  },
  {
    id: 15,
    nickname: "Lilja",
    lastWatered: "2026-02-15",
    waterFrequency: 6,
    trefleId: 131313,
    commonName: "Lily",
    scientificName: "Lilium",
    familyCommonName: "Liliaceae",
    image: "/assets/plant15.png",
  },
  {
    id: 16,
    nickname: "Pion",
    lastWatered: "2026-02-16",
    waterFrequency: 8,
    trefleId: 141414,
    commonName: "Peony",
    scientificName: "Paeonia",
    familyCommonName: "Paeoniaceae",
    image: "/assets/plant16.png",
  },
  {
    id: 17,
    nickname: "Magnolia",
    lastWatered: "2026-02-17",
    waterFrequency: 10,
    trefleId: 151515,
    commonName: "Magnolia",
    scientificName: "Magnolia",
    familyCommonName: "Magnoliaceae",
    image: "/assets/plant17.png",
  },
  {
    id: 18,
    nickname: "Hortensia",
    lastWatered: "2026-02-18",
    waterFrequency: 4,
    trefleId: 161616,
    commonName: "Hydrangea",
    scientificName: "Hydrangea",
    familyCommonName: "Hydrangeaceae",
    image: "/assets/plant18.png",
  },
  {
    id: 19,
    nickname: "Dahlia",
    lastWatered: "2026-02-19",
    waterFrequency: 5,
    trefleId: 171717,
    commonName: "Dahlia",
    scientificName: "Dahlia",
    familyCommonName: "Asteraceae",
    image: "/assets/plant19.png",
  },
  {
    id: 20,
    nickname: "Gerbera",
    lastWatered: "2026-02-20",
    waterFrequency: 7,
    trefleId: 181818,
    commonName: "Gerbera",
    scientificName: "Gerbera",
    familyCommonName: "Asteraceae",
    image: "/assets/plant20.png",
  },
];
